# Generated by Django 5.2 on 2025-05-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_parent',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
