# Generated by Django 5.2 on 2025-06-07 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_option_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='option',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filiere'),
        ),
    ]
