# Generated by Django 5.2 on 2025-06-07 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_etudiant_option_etudiant_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='filiere',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.option'),
        ),
    ]
