# Generated by Django 5.2 on 2025-06-07 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_etudiant_filiere_etudiant_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filiere'),
        ),
    ]
